"""empty message

Revision ID: 021ed601c45b
Revises: f58b14a037ba
Create Date: 2019-09-30 22:28:54.740714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021ed601c45b'
down_revision = 'f58b14a037ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'stack_trace')
    op.drop_column('log', 'payload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('payload', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('log', sa.Column('stack_trace', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
