# pylint: skip-file
"""empty message

Revision ID: 0c965813a881
Revises: d5904e6abbb5
Create Date: 2019-11-08 21:53:26.092077

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0c965813a881'
down_revision = 'd5904e6abbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_device', 'positive_state')
    op.drop_column('executive_device', 'negative_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_device',
                  sa.Column('negative_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('executive_device',
                  sa.Column('positive_state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
