"""empty message

Revision ID: 11446b6baf42
Revises: c78de455382a
Create Date: 2019-10-28 11:40:57.534586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11446b6baf42'
down_revision = 'c78de455382a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executive_device', 'is_formula_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executive_device', 'is_formula_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
