# pylint: skip-file
"""empty message

Revision ID: 138e86893b6a
Revises: 0c965813a881
Create Date: 2019-11-08 21:53:53.168266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138e86893b6a'
down_revision = '0c965813a881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_device', sa.Column('negative_state', sa.Float(), nullable=True))
    op.add_column('executive_device', sa.Column('positive_state', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_device', 'positive_state')
    op.drop_column('executive_device', 'negative_state')
    # ### end Alembic commands ###
