# pylint: skip-file
"""empty message

Revision ID: 39ec29539f26
Revises: 138e86893b6a
Create Date: 2019-11-09 13:45:49.160575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ec29539f26'
down_revision = '138e86893b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_type', sa.Column('default_state', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_type', 'default_state')
    # ### end Alembic commands ###
