"""empty message

Revision ID: 4ba3698a8641
Revises: f5d6fb482e96
Create Date: 2019-10-06 15:30:46.249846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba3698a8641'
down_revision = 'f5d6fb482e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'name')
    # ### end Alembic commands ###
