"""empty message

Revision ID: 50446fa84014
Revises: 087dd125ce10
Create Date: 2019-10-26 18:47:52.237988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50446fa84014'
down_revision = '087dd125ce10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sensor', ['device_group_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor', type_='unique')
    # ### end Alembic commands ###
