"""empty message

Revision ID: 63cfffbc643d
Revises: 138e86893b6a
Create Date: 2019-11-09 14:47:52.300453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cfffbc643d'
down_revision = '138e86893b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_key', sa.String(length=255), nullable=False),
    sa.Column('device_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deleted_device')
    # ### end Alembic commands ###
