# pylint: skip-file
"""empty message

Revision ID: 9194b7ca7b67
Revises: a7e4f26f4ad5
Create Date: 2019-10-27 15:27:20.393326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9194b7ca7b67'
down_revision = 'a7e4f26f4ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('formula_name_key', 'formula', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('formula_name_key', 'formula', ['name'])
    # ### end Alembic commands ###
