"""empty message

Revision ID: a26657686ab1
Revises: eb6ff7638206
Create Date: 2019-10-16 11:21:27.368585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26657686ab1'
down_revision = 'eb6ff7638206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_reading', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_reading', 'date')
    # ### end Alembic commands ###
