# pylint: skip-file

"""empty message

Revision ID: c14350fe3b5e
Revises: 021ed601c45b
Create Date: 2019-09-30 22:29:26.915069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14350fe3b5e'
down_revision = '021ed601c45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('payload', sa.Text(), nullable=True))
    op.add_column('log', sa.Column('stack_trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'stack_trace')
    op.drop_column('log', 'payload')
    # ### end Alembic commands ###
