# pylint: skip-file

"""empty message

Revision ID: c20455a1e062
Revises: ee18a873a99d
Create Date: 2019-10-26 19:19:31.836570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20455a1e062'
down_revision = 'ee18a873a99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('executive_device_device_group_id_name_key', 'executive_device', type_='unique')
    op.drop_constraint('executive_type_device_group_id_name_key', 'executive_type', type_='unique')
    op.drop_constraint('reading_enumerator_sensor_type_id_number_key', 'reading_enumerator', type_='unique')
    op.drop_constraint('sensor_device_group_id_name_key', 'sensor', type_='unique')
    op.drop_constraint('sensor_type_device_group_id_name_key', 'sensor_type', type_='unique')
    op.drop_constraint('state_enumerator_executive_type_id_number_key', 'state_enumerator', type_='unique')
    op.drop_constraint('user_group_device_group_id_name_key', 'user_group', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_group_device_group_id_name_key', 'user_group', ['device_group_id', 'name'])
    op.create_unique_constraint('state_enumerator_executive_type_id_number_key', 'state_enumerator', ['executive_type_id', 'number'])
    op.create_unique_constraint('sensor_type_device_group_id_name_key', 'sensor_type', ['device_group_id', 'name'])
    op.create_unique_constraint('sensor_device_group_id_name_key', 'sensor', ['device_group_id', 'name'])
    op.create_unique_constraint('reading_enumerator_sensor_type_id_number_key', 'reading_enumerator', ['sensor_type_id', 'number'])
    op.create_unique_constraint('executive_type_device_group_id_name_key', 'executive_type', ['device_group_id', 'name'])
    op.create_unique_constraint('executive_device_device_group_id_name_key', 'executive_device', ['device_group_id', 'name'])
    # ### end Alembic commands ###
