"""empty message

Revision ID: c33161de6380
Revises: 4ba3698a8641
Create Date: 2019-10-12 11:40:48.300400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33161de6380'
down_revision = '4ba3698a8641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unconfigured_device', 'device_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unconfigured_device', 'device_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
