# pylint: skip-file
"""empty message

Revision ID: d5904e6abbb5
Revises: 589274cf0b50
Create Date: 2019-11-08 21:51:03.148529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5904e6abbb5'
down_revision = '589274cf0b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_device', sa.Column('state', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_device', 'state')
    # ### end Alembic commands ###
