"""empty message

Revision ID: eb6ff7638206
Revises: c33161de6380
Create Date: 2019-10-14 19:54:27.618250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6ff7638206'
down_revision = 'c33161de6380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executive_device', sa.Column('is_formula_used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executive_device', 'is_formula_used')
    # ### end Alembic commands ###
