"""empty message

Revision ID: ee18a873a99d
Revises: e3e33f1611c3
Create Date: 2019-10-26 18:55:48.056182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee18a873a99d'
down_revision = 'e3e33f1611c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'executive_type', ['device_group_id', 'name'])
    op.create_unique_constraint(None, 'reading_enumerator', ['sensor_type_id', 'number'])
    op.create_unique_constraint(None, 'sensor_type', ['device_group_id', 'name'])
    op.create_unique_constraint(None, 'state_enumerator', ['executive_type_id', 'number'])
    op.create_unique_constraint(None, 'user_group', ['device_group_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group', type_='unique')
    op.drop_constraint(None, 'state_enumerator', type_='unique')
    op.drop_constraint(None, 'sensor_type', type_='unique')
    op.drop_constraint(None, 'reading_enumerator', type_='unique')
    op.drop_constraint(None, 'executive_type', type_='unique')
    # ### end Alembic commands ###
