"""empty message

Revision ID: f5d6fb482e96
Revises: c14350fe3b5e
Create Date: 2019-10-06 15:30:23.797756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d6fb482e96'
down_revision = 'c14350fe3b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_group_name_key', 'user_group', type_='unique')
    op.drop_column('user_group', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_group_name_key', 'user_group', ['name'])
    # ### end Alembic commands ###
